version: "3.9"
x-wordpress-variables: &wordpress-variables
  WORDPRESS_DB_HOST: ${DB_HOST}
  WORDPRESS_DB_USER: ${DB_USER}
  WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
  WORDPRESS_DB_NAME: ${DB_NAME}
  WORDPRESS_CONFIG_EXTRA: |
    define( 'WP_HOME', 'http://localhost:${WP_PORT}' );
    define( 'WP_SITEURL', 'http://localhost:${WP_PORT}' );
    define( 'FS_METHOD', '${FS_METHOD}' );
    define( 'WP_ENVIRONMENT_TYPE', '${WP_ENVIRONMENT_TYPE:-production}' );
    define( 'SCRIPT_DEBUG', ${DEBUG} );
    define( 'WP_DISABLE_FATAL_ERROR_HANDLER', false );
    define( 'WP_DEBUG_DISPLAY', false );
    define( 'WP_DEBUG_LOG', false );
    define( 'DISALLOW_FILE_EDIT', ${DISALLOW_FILE_EDIT} );
services:
  db:
    container_name: "${PROJECT}_db"
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      # === Init DB with dump file, 1st time only! ===
      # - ./mysql.sql:/docker-entrypoint-initdb.d/init_dump.sql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  wordpress:
    container_name: "${PROJECT}_wp"
    depends_on:
      - db
    image: wordpress:${WP_VERSION}
    ports:
      - "${WP_PORT}:80"
    restart: always
    user: 1000:1000
    volumes:
      - ./plugin/:/var/www/html/wp-content/plugins/${PROJECT}
      - ./uploads/:/var/www/html/wp-content/uploads/
      - ./upgrade/:/var/www/html/wp-content/upgrade/
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
    environment: *wordpress-variables
  front:
    container_name: "${PROJECT}_front"
    image: node:16-slim
    working_dir: /app
    volumes:
      - ./:/app
    # command: "/bin/bash -c 'yarn install && yarn run watch'"
    command: tail -f /dev/null
    depends_on:
      - wordpress
  phpmyadmin:
    container_name: "${PROJECT}_pma"
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
  wp-cli:
    container_name: "${PROJECT}_wp-cli"
    image: wordpress:cli
    entrypoint: ['/bin/sh']
    user: 1000:1000
    stdin_open: true
    tty: true
    volumes:
      - ./scripts/:/var/www/html/scripts
    volumes_from:
      - wordpress
    depends_on:
      - db
    environment: *wordpress-variables
volumes:
  db_data: {}
